### ISSUE TITLE
BUSINESS_VERIFICATION_FAILED, HmsMapKit_TileCache_38: startUrlRequest Identity fail ,do not has permission get tile. authResult :060011

### ISSUE THREAD

**Issue by Zhuinden** [HMS-Core/hms-mapkit-demo#13]
```
2020-12-21 16:28:40.534 17210-19883/ E/HmsMapKit_ErrorTraceLogPusher_4: cache error trace log : ErrorTraceLogDTO{ scenario = ACCESS_MAP_SERVICE_ERROR', message='010010 : BUSINESS_VERIFICATION_FAILED'}
    com.huawei.hms.maps.foundation.client.mab: *1*0*0*:*B*S*N*S*_*E*I*I*A*I*N*F*I*E*
2020-12-21 17:04:56.073 23913-24850/ I/HmsMapKit_AuthenticateClient_289: authenticate requestId is : 103535075authenticate20201221170456062378458
2020-12-21 17:04:56.154 23913-24850/ D/HmsMapKit_AuthenticateClient_75: response code : 401
2020-12-21 17:04:56.157 23913-24850/ E/HmsMapKit_ErrorCodeConsts_208: No matching return code is found. Build a new one, code is .010002
2020-12-21 17:04:56.159 23913-24850/ D/HmsMapKit_AccessTraceLogPusher_6343: cache access trace log: AccessTraceLogDTO{ requestId='103535075authenticate20201221170456075717173', apiName='MapView.onCreate', errorCode='010002', startTime=1608566696073, endTime=1608566696158}
2020-12-21 17:04:56.161 23913-24850/ E/HmsMapKit_ErrorTraceLogPusher_105: cache error trace log : ErrorTraceLogDTO{ scenario = ACCESS_MAP_SERVICE_ERROR', message='010002 : Unknown Code - 010002'}
    com.huawei.hms.maps.foundation.client.b: *1*0*2*:*U*k*o*n*C*d* * *1*0*2
        at com.huawei.hms.maps.foundation.client.b$a.a(:89)
        at com.huawei.hms.maps.foundation.client.c.d(:173)
        at com.huawei.hms.maps.foundation.client.c.e(:75)
        at com.huawei.hms.maps.maproute.client.auth.b.b(:43)
        at com.huawei.hms.maps.maproute.cache.a$a.c(:289)
        at com.huawei.hms.maps.maproute.cache.a$a.call(:5272)
        at ev.d(:42)
        at dU.e(:12025)
        at eB$e.run(:96)
        at dX$e.run(:571)
        at eM.run(:66)
        at eM.call(:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
2020-12-21 17:04:56.163 23913-24850/ D/HmsMapKit_ErrorTraceLogPusher_105: logLength is 875
2020-12-21 17:04:56.164 23913-24850/ D/HmsMapKit_ErrorTraceLogPusher_1092: analyticsInstance.onEvent(), eventId is map_errorlog_report, valueMap.size() is 15
2020-12-21 17:04:56.166 23913-24850/ I/HiAnalytics/event: [2020-12-21 17:04:56.165 I/hianalytics/HiAnalytics/event 23913:1400 null:13] HiAnalyticsInstance.onEvent(int type, String eventId, Map<String, String> mapValue) is execute.TAG: hms_map,TYPE: 1
2020-12-21 17:04:56.169 23913-24850/ E/HmsMapKit_AuthenticateCache_293: authenToServer ClientAccessException
2020-12-21 17:04:56.170 23913-24850/ E/HmsMapKit_ErrorTraceLogPusher_6324: cache error trace log : ErrorTraceLogDTO{ scenario = AUTHENTICATE', message='INTERNAL_ERRORauthenToServer ClientAccessException'}
2020-12-21 17:04:56.172 23913-24850/ D/HmsMapKit_ErrorTraceLogPusher_1092: analyticsInstance.onEvent(), eventId is map_errorlog_report, valueMap.size() is 14
2020-12-21 17:04:56.173 23913-24850/ I/HiAnalytics/event: [2020-12-21 17:04:56.172 I/hianalytics/HiAnalytics/event 23913:1400 null:13] HiAnalyticsInstance.onEvent(int type, String eventId, Map<String, String> mapValue) is execute.TAG: hms_map,TYPE: 1
2020-12-21 17:04:56.175 23913-23913/ D/HmsMapKit_AuthenticateCache_63: result is 060011 : INTERNAL_ERROR
```

We have created the project on AGConnect, added the SHA256 for an SHA256withRSA keystore, signed the app with said keystore, run the app, and we're getting the error

```
log : ErrorTraceLogDTO{ scenario = AUTHENTICATE', message='INTERNAL_ERRORauthenToServer ClientAccessException'}
D/HmsMapKit_AuthenticateCache_63: result is 060011 : INTERNAL_ERROR
```

Please advise what we are missing, we've been trying to fix this for a week now.

**Comment by Zhuinden** [comment]
Certificate signature was missing on the Credentials page on AG Connect website.
